package com.sangardas.snapshotdirector.aws.dynamodb.model;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.util.json.Jackson;

@DynamoDBTable(tableName="Users")
public class User {

	private final Map<String, Object> attributes = new LinkedHashMap<String, Object>();
	
	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public void setId(String id){
		attributes.put("Id", id);
	}
	public String getId(){
		return (String) attributes.get("Id");
	}
	
	@DynamoDBAttribute(attributeName="userName")
	public void setUserName(String userName){
		attributes.put("userName", userName);
	}
	public String getUserName(){
		return (String) attributes.get("userName");
	}
	
	@DynamoDBAttribute(attributeName="password")
	public void setPassword(String password){
		attributes.put("password", password);
	}
	public String getPassword(){
		return (String) attributes.get("password");
	}
	
	@DynamoDBAttribute(attributeName="groups") //TODO: Change the type of attribute to List<String>
	public void setGroups(String groups){
		attributes.put("groups", groups);
	}
	public String getGroups(){
		return (String) attributes.get("groups");
	}
	
	@Override
	public String toString() {
		Map<String, Object> passwordlessUserInfo = new LinkedHashMap<String, Object>();
		passwordlessUserInfo.putAll(attributes);
		passwordlessUserInfo.put("password", "");
		return Jackson.toJsonString(passwordlessUserInfo);
	}
	
}
