package com.sungardas.snapdirector.aws.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Snapshots")
public class Snapshot {

	@DynamoDBAutoGeneratedKey
	@DynamoDBIndexHashKey(attributeName="id")
	private String id;
	
	@DynamoDBAttribute(attributeName="snapshotId")
	private String snapshotId;
	
	@DynamoDBAttribute(attributeName="volumeId")
	private String volumeId;
	
	public Snapshot(){}
	
	public Snapshot(String snapshotId, String volumeId){
		this.snapshotId = snapshotId;
		this.volumeId = volumeId;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSnapshotId() {
		return snapshotId;
	}

	public void setSnapshotId(String snapshotId) {
		this.snapshotId = snapshotId;
	}

	public String getVolumeId() {
		return volumeId;
	}

	public void setVolumeId(String volumeId) {
		this.volumeId = volumeId;
	}
	
	
	
}
